# Generated by Django 4.2.7 on 2023-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(null=True),
        ),
    ]
